#!/usr/bin/expect

spawn yo hubot
expect "(Y/n)"
send "n\r"
expect ":"
send "\r"
expect "(hubot)"
send "\r"
expect "(A simple helpful robot for your Company)"
send "\r"
expect "(campfire)"
send "hipchat\r"
expect eof

